import type { CloudArenaDeckPreset } from "../types.js";

export const mixedGuardianDeckPreset: CloudArenaDeckPreset = {
  id: "mixed_guardian",
  label: "Mixed Guardian",
  cards: [
    "guardian",
    "token_angel",
    "focused_blessing",
    "graveyard_hymn",
    "targeted_smite",
    "targeted_strike",
    "forced_sacrifice",
    "attack",
    "defend",
    "token_angel",
    "attack",
    "choir_captain",
    "sanctified_guide",
    "holy_blade",
    "forbidden_insight",
    // "sacrificial_seraph",
    "defend",
    "attack",
    "token_angel",
    "defend",
    // "anointed_banner",
    "mass_benediction",
    "attack",
    "attack",
    "defend",
    "defending_strike",
  ],
};
