import type { CloudArenaDeckPreset } from "../types.js";

export const tallCreaturesDeckPreset: CloudArenaDeckPreset = {
  id: "tall_creatures",
  label: "Tall Creatures",
  cards: [
    "guardian",
    "guardian",
    "sacrificial_seraph",
    "sacrificial_seraph",
    "holy_blade",
    "holy_blade",
    "focused_blessing",
    "focused_blessing",
    "sanctified_guide",
    "sanctified_guide",
    "defending_strike",
    "defending_strike",
    "targeted_strike",
    "targeted_strike",
    "targeted_strike",
    "forbidden_insight",
    "forbidden_insight",
    "graveyard_hymn",
    "graveyard_hymn",
    "attack",
    "attack",
    "attack",
    "defend",
    "defend",
    "defend",
  ],
};
