import type { CloudArenaDeckPreset } from "../types.js";

export const wideAngelsDeckPreset: CloudArenaDeckPreset = {
  id: "wide_angels",
  label: "Wide Angels",
  cards: [
    "token_angel",
    "token_angel",
    "token_angel",
    "token_angel",
    "token_angel",
    "token_angel",
    "token_angel",
    "token_angel",
    "focused_blessing",
    "focused_blessing",
    "focused_blessing",
    "focused_blessing",
    "focused_blessing",
    "mass_benediction",
    "mass_benediction",
    "mass_benediction",
    "anointed_banner",
    "anointed_banner",
    "choir_captain",
    "choir_captain",
    "sanctified_guide",
    "sanctified_guide",
    "guardian",
    "guardian",
    "attack",
    "attack",
    "defend",
    "defend",
  ],
};
